alias el="eza -la"
alias e="eza"
alias reload="source ~/.config/fish/config.fish"
alias tis="timew summary :ids"
alias editconfig="vim ~/Code/.dotfiles/fish/osx.config.fish"
alias derek="ssh-add ~/.ssh/dereksione_gh"
alias wes="ssh-add ~/.ssh/wesrer_gh"
alias carb="cargo build"
alias carr="cargo run"
alias cart="cargo test"
alias up="brew update & brew upgrade"

# Bullpen specific commands
alias tbull="task project:bullpen"
alias tbulla="task add project:bullpen"
alias tbullx="task project:bullpen done"
