alias el="eza -la"
alias e="eza"
alias reload="source ~/.config/fish/config.fish"
alias tis="timew summary :ids"
alias editconfig="vim ~/Code/.dotfiles/fish/osx.config.fish"
alias tbull="task project:bullpen"
alias derek="ssh-add ~/.ssh/dereksione_gh"
alias wes="ssh-add ~/.ssh/wesrer_gh"
